### ISSUE TITLE
Freezing regexp cause .exec to throw

### ISSUE THREAD

**Issue by otakustay** [tiaanduplessis/colors-regex#1]
```
TypeError: Cannot assign to read only property 'lastIndex' of object '[object RegExp]'
```

It seems `RegExp#exec` requires a non readonly `lastIndex` property

**Comment by otakustay** [comment]
@tiaanduplessis The core problem of this issue is whether we must freeze these regexps, if simply remove `.freeze` calls is possible, I can provide a PR

**Comment by tiaanduplessis** [comment]
@otakustay thanks for debugging the issue. Would be happy to accept a PR 😄

**Comment by tiaanduplessis** [comment]
@otakustay I've removed the freeze in v2.0.0 👍
